apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
data:
  # TODO: set up all secrets and passwords here...
  password: {{ .Values.general.superUser.password | b64enc }}
  smtp.password: {{ .Values.smtp.password | b64enc }}
